### ISSUE TITLE
Reservation register error when adding Logs

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/tfexplorer#106]
The following error occurred when creating then registering a reservation with logs details for a container
```
requests.exceptions.HTTPError: 400 Client Error: json: cannot unmarshal array into Go struct field Logs.data_reservation.containers.logs.data of type workloads.LogsRedis for url: https://explorer.testnet.grid.tf/explorer/reservations
```
The steps:
 - Update container schema `tfgrid.workloads.reservation.container.1` to include logs matching the updated schema in https://github.com/threefoldtech/tfexplorer/blob/master/models/schema/workloads/tfgrid_workloads_reservation_container_1.toml 
```
logs = (LO) !tfgrid.workloads.reservation.container.logs.1

@url = tfgrid.workloads.reservation.container.logs.1
type = (S)
data = (LO) !tfgrid.workloads.reservation.container.logsredis.1

@url = tfgrid.workloads.reservation.container.logsredis.1
stdout = (S)
stderr = (S)
```
- Create the reservation and add a container, then add the logs as follows:
```
        cont_logs = container_created.logs.new()
        cont_logs.type = "redis"
        cont_logs_data = cont_logs.data.new()
        cont_logs_data.stdout = f"redis://{IP}:{REDIS_PORT}/container-stdout"
        cont_logs_data.stderr = f"redis://{IP}:{REDIS_PORT}/container-stderr"
```
- Register the reservation using `j.sal.zosv2.reservation_register(...)`

**Comment by zaibon** [comment]
@maxux

**Comment by maxux** [comment]
Why `data = (LO)` ? Data is not a list. It's an object.

**Comment by ranatrk** [comment]
> Why `data = (LO)` ? Data is not a list. It's an object.

 It worked with the data as an object, thank you :D
I did it based on the schema mentioned in the description.I geuss it should be updated in both repos right?

**Comment by maxux** [comment]
Yep, this model was never really used until now. Just changing from `LO` to `O` do the trick ?

**Comment by ranatrk** [comment]
yes, and the reservation was successful
