### ISSUE TITLE
Payment issue

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/tfexplorer#122]
trying to pay reservation in freetft but it gets me this

3bot username : tfwallet.3bot
reservation period : 2 years
wallet has 5000 freetft
farm : freefarm

<img width="1433" alt="Screen Shot 2020-07-13 at 2 20 31 PM" src="https://user-images.githubusercontent.com/13523434/87406564-29de0e80-c5c1-11ea-9b41-a6efdc3b3355.png">

![photo_2020-07-14_10-52-24](https://user-images.githubusercontent.com/13523434/87406567-2b0f3b80-c5c1-11ea-864b-d7a3fe5b9af9.jpg)

<img width="1433" alt="Screen Shot 2020-07-13 at 2 21 17 PM" src="https://user-images.githubusercontent.com/13523434/87406572-2cd8ff00-c5c1-11ea-95c0-d43fc0a0c231.png">

**Comment by zaibon** [comment]
@PeterNashaat Can you confirum you are trying to deploy workloads on testnet ?

Cause I can see the payment address exists on stellar testnet. 
And you are trying to pay with the 3bot connect app which only talk to stellar mainnet.

**Comment by PeterNashaat** [comment]
@zaibon thanks, i was actually creating on testnet, but now i'm facing a new issue when registering my 3bot id on mainnet
- commands 
```
JS-NG> myid = j.core.identity.new(name="mainnet", tname="tfproduction.3bot", email="tf-production@threefold.io", explorer_url="https://explorer.grid.tf/explorer/", words="")

JS-NG> myid.register()

```
- error

```
  File "/root/sandbox/code/threefoldtech/js-sdk/jumpscale/clients/explorer/users.py", line 29, in register
    return resp.json()['id']
           └ <Response [200]>
TypeError: list indices must be integers or slices, not str

list indices must be integers or slices, not str

```
