### ISSUE TITLE
updating old networks fail on testnet after migration

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfexplorer#136]
updating old networks fail on testnet after the migration (seems that some nodes which were part of the network did not send any results for the workloads

**Comment by m-motawea** [comment]
this is a workload related to a migrated network I think
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/462999

this workload is for a new network with no result as well
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/463033

**Comment by zaibon** [comment]
Should be fixed by https://github.com/threefoldtech/zos/commit/d7bb61e03d36067ec8823c3b6d8fd583c081c1c2
This commit is deployed on devnet and testnet
