### ISSUE TITLE
Error after migrating to capacitypools from old workloads

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/tfexplorer#152]
tid: 414
Explorer: Testnet
Error:
![Screenshot from 2020-08-25 15-31-21](https://user-images.githubusercontent.com/10658229/91180515-178ae080-e6e8-11ea-8600-95e9391c7ee3.png)

```
{"error": "401 Client Error: {\"error\":\"unauthorized access: signature verification failed\"}\n for url: https://explorer.testnet.grid.tf/api/v1/reservations/convert"}
```

This workload fails to delete https://explorer.testnet.grid.tf/api/v1/reservations/workloads/463072

![Screenshot from 2020-08-25 15-37-43](https://user-images.githubusercontent.com/10658229/91181207-f24aa200-e6e8-11ea-8c18-eff6a4efa72e.png)

**Comment by zaibon** [comment]
Can you tell me when did you do the migration ?
This is a bug that should already be fixed by now.

**Comment by waleedhammam** [comment]
> Can you tell me when did you do the migration ?
> This is a bug that should already be fixed by now.

it was on 19 June

**Comment by zaibon** [comment]
Added the missing pieces in https://github.com/threefoldtech/tfexplorer/pull/153
Fixed version has been pused to devnet and testnet.

@waleedhammam can you retry to delete your workload that was giving issue please ?

**Comment by waleedhammam** [comment]
Yes this one fixed, thanks. also the unauthorized access for has migrated.

But I got an error from a recent workload after migration while I was trying to delete it, is that related ? 

https://explorer.testnet.grid.tf/api/v1/reservations/workloads/469085
![Screenshot from 2020-08-26 10-28-43](https://user-images.githubusercontent.com/10658229/91280539-24124600-e787-11ea-8678-f3d0e5136116.png)

**Comment by zaibon** [comment]
@waleedhammam this new error is not related, Please open a new issue fo it and close this one if it's working now.

**Comment by waleedhammam** [comment]
> @waleedhammam this new error is not related, Please open a new issue fo it and close this one if it's working now.

Okay, thank you
