### ISSUE TITLE
it takes too long to extend a pool

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfexplorer#159]
it takes ~ 10 mins to extend a pool (tried on 5 6 pools already)

Duplicate of #263

**Comment by LeeSmet** [comment]
Do you happen to have some more info (pool ID, rough estimate of the time this happened, ...)? Just tried it myself and it seems to work fine, my pool was updated after about half a minute (note that delays of 1 minute are possible due to the way payments work)

**Comment by m-motawea** [comment]
I experienced this lag two days ago (1/9) around 10 pm utc. I think the pool I was extending was this one
https://explorer.testnet.grid.tf/api/v1/reservations/pools/6

**Comment by xmonader** [comment]
my pool was 975 https://explorer.testnet.grid.tf/api/v1/reservations/pools/975 (so proud i remembered it now) :D it was around the same time too of @m-motawea  and also that issue happened with @muhamadazmy
