### ISSUE TITLE
tfexplorer uses up all system resources under load

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/tfexplorer#17]
with a few observations :
- better log directly into a file instead of relying on journald (in case of stand-alone systemd-unit)
- it seems the load is mosly because of parsing a lot of fata comong from mongo (output of bw of mongo container is on average +30MByte/sec
- front traffic is OK, around 25KBye/sec

![image](https://user-images.githubusercontent.com/5995555/80221562-c1c4ff80-8645-11ea-951e-e7cd9653df7f.png)

![image](https://user-images.githubusercontent.com/5995555/80221731-fdf86000-8645-11ea-8089-7f534695ff80.png)

**Comment by zaibon** [comment]
related to #36

**Comment by zaibon** [comment]
fixed by #40 and #56
