### ISSUE TITLE
Prepare for the next stellar protocol upgrade

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/tfexplorer#182]
https://www.stellar.org/developers-blog/guide-to-protocol-14-prep

**Comment by LeeSmet** [comment]
@zaibon I assume this was done in 046188aa3f9383fdb5e17f420e6d62f5fb4ba18a?

**Comment by zaibon** [comment]
Right. I kept this open to make sure we do not forget to deploy on mainnet
