### ISSUE TITLE
Deployment on testnet fails with latest sdk development

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/tfexplorer#185]
Deploying on testnet nodes failes due to `failed to decrypt secret env var 'POSTGRES_PASSWORD': decryption error`

example wid: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/490518

how to reproduce:

- Deploy any container on testnet with secret env
- JS-SDK version: Latest development

**Comment by zaibon** [comment]
can you give the full code that is used to deploy please. I did updated all the places I know of where we do encryption, but maybe they are some I do not now about.

**Comment by waleedhammam** [comment]
> can you give the full code that is used to deploy please. I did updated all the places I know of where we do encryption, but maybe they are some I do not now about.

It's now on development_testnet. I got this error msg once, and then for the other workloads the node refused to accept the reservation

**Comment by zaibon** [comment]
Can your give the code anyhow please

**Comment by waleedhammam** [comment]
here's the encryption code https://github.com/threefoldtech/js-sdk/commit/c8588e546e09f942934a45dad7a111286eb977db
and used that chatflow: https://github.com/threefoldtech/js-sdk/blob/development_testnet/jumpscale/packages/marketplace/chats/gitea.py

explorer client and zos sal from the same branch here: https://github.com/threefoldtech/js-sdk/tree/development_testnet

**Comment by zaibon** [comment]
@waleedhammam where does the encryption of the data you pass to the `secret_enviroment` field happens ?

**Comment by waleedhammam** [comment]
> @waleedhammam where does the encryption of the data you pass to the `secret_enviroment` field happens ?

In this part: https://github.com/threefoldtech/js-sdk/blob/development_testnet/jumpscale/sals/reservation_chatflow/deployer.py#L842
