### ISSUE TITLE
Failed to deploy on testnet

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/tfexplorer#194]
Can't find resources to deploy on testnet (mainly storage, a public ipv4 node, a public ipv6 node)

https://github.com/threefoldtech/js-sdk/blob/ef00a2dea91ef5629ba11c486c347ccc6f350841/jumpscale/sals/marketplace/apps_chatflow.py#L92

![Screenshot from 2020-10-18 12-12-23](https://user-images.githubusercontent.com/10658229/96365929-7e56d400-1144-11eb-8af9-5841c5043453.png)

**Comment by zaibon** [comment]
Are you suggesting there is something wrong with the explorer behavior? The way how the capacity planning is done by the chatflow is not controlled by the explorer.

**Comment by waleedhammam** [comment]
> Are you suggesting there is something wrong with the explorer behavior? The way how the capacity planning is done by the chatflow is not controlled by the explorer.

It's OK but can't find resources.
