### ISSUE TITLE
show both testnet and mainnet nodes on  explorer.grid.tf

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/tfexplorer#200]
by kds / stakeholder request:

at the moment we are showing node at 2 different explorer:
testnet: explorer.testnet.grid.tf 
mainnet: explorer.grid.tf

As a user I want to go to one domain / website and see all / both available testnet nodes and mainnet nodes, depending on what I choose to see.

solution:
make explorer.grid.tf show nodes both testnet and mainnet.
possibilities:
colour coded, testnet section and mainnet section, etc

**Comment by zaibon** [comment]
We will not implement something like that.
The explorer manage one network and that's it hacking there is not worth it. 

If your goal is to have a view with the nodes in one page just build a small website that gets its data from the different explorer API. Will be way easier and faster to implement.

**Comment by sasha-astiadi** [comment]
moved to a better solution suggestion on: https://github.com/threefoldtech/home/issues/924
