### ISSUE TITLE
Update CU/SU and TFT pricing on Explorer

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/tfexplorer#215]
pls update the pricing for CU/SU in the Explorer to EUR 10 for CU and EUR 8 for SU. Use USD 0.5 TFT price to calculate the amount of TFT for CU/SU. Exchange rate usd2eur: 1.18

for more details see: https://wiki.threefold.io/#/grid_pricing

pls add the link to https://wiki.threefold.io/#/grid_pricing on the explorer gui as 'Current Capacity Pricing'

**Comment by muhamadazmy** [comment]
@andhartl do you mean TFT is 0.5 USD or 0.05 ?

**Comment by andhartl** [comment]
mean 0.05 USD TFT price. Sorry for the typo

**Comment by despiegk** [comment]
please point to the code

**Comment by xmonader** [comment]
@despiegk code in https://github.com/threefoldtech/tfexplorer/pull/216

**Comment by muhamadazmy** [comment]
We also added the prices to the explorer UI but still not updated yet
