### ISSUE TITLE
UI: show current prices as built in the explorer in the UI  

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/tfexplorer#217]
- There should be an api endpoint that returns the built in prices as configured in the explorer 
- The UI should render these prices in the top bar
- This should also be shown in the global explorer UI which shows resources from all networks

**Comment by LeeSmet** [comment]
I don't think the explorer is the place to show this. The explorer is and has always been there to discover capacity. There is nothing regarding reservation on there.

Also, there is currently a static price, but the idea is that farmers will be able to set their own price in the future (at least certified farmers will), so a single static price is not really future proof.

If prices are really needed, it might be best to render them on the nodes themselves imo

**Comment by muhamadazmy** [comment]
@LeeSmet actually I got this as a feature request from @andhartl . But indeed showing it per farm (or node) is better for the future

**Comment by DylanVerstraete** [comment]
I second Lee's opinion, we should only start showing prices when the farmer is able to set them.

**Comment by DylanVerstraete** [comment]
Added on unified view as well:

https://github.com/threefoldtech/nodes-explorer/pull/2 can be merged if https://github.com/threefoldtech/tfexplorer/pull/224 is merged.
