### ISSUE TITLE
Capacity pools report wrong amount of consumed SU

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/tfexplorer#221]
Pool 1 report a consumption of ~ 1.29 SU/sec
But all the actives workloads linked to it are NetworkResource which do NOT consume any SU.

```python
JS-NG> pool = zos.pools.get(1)                                                                      
JS-NG> pool.active_su                                                                                                                                                                                    
1.2968749999999956
JS-NG> workloads_type = set()                                                                                                                                                                            
JS-NG> for wid in pool.active_workload_ids: 
     2     w = zos.workloads.get(wid) 
     3     workloads_type.add(w.info.workload_type.name)                                                                                                                                                 
JS-NG> workloads_type                                                                               
{'Network_resource'}
```

**Comment by DylanVerstraete** [comment]
We don't have a concept of network resources atm. How could this be possible?

**Comment by zaibon** [comment]
I'm talking about the primitive [NetworkResource](https://github.com/threefoldtech/js-sdk/blob/03c71523de5fc3f89743fce0f608e11015f51c50/jumpscale/clients/explorer/models.py#L507), not the resource unit for network

**Comment by DylanVerstraete** [comment]
Yes I know but I wonder how we the explorer could count this wrongly because we dont count network resources..

**Comment by DylanVerstraete** [comment]
As you said, network resources dont consume SU

**Comment by zaibon** [comment]
> Yes I know but I wonder how the explorer could count this wrongly because we dont count network resources..

Well that's exactly why I open this issue :-P
I used to have other workloads running, so this probably happened over time from other workloads that actually consumes ressources
