### ISSUE TITLE
can't extend an empty pool on testnet

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/tfexplorer#227]
pool http://explorer.testnet.grid.tf/api/v1/reservations/pools/5431
we do the payment but no resources are added to the pool. 

note: the pool has other weird values:

- it has expired but the `empty_at` value isn't reset and shows a value in the past `11/30/2020 @ 10:48am (UTC)` . 
- it also shows active sus but there isn't any active workload (except for network resources) in the pool after it has expired.|

**Comment by muhamadazmy** [comment]
Why this was reopened, i checked the pool and the values seems to be correct.
