### ISSUE TITLE
Error deploying kubernetes on devnet

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/tfexplorer#229]
`"message": "failed to install k3s: failed to install vm in 5 minutes"`

https://explorer.devnet.grid.tf/api/v1/reservations/workloads/2266

**Comment by muhamadazmy** [comment]
- We are adding part of the vm logs on failure here https://github.com/threefoldtech/zos/pull/1092 
- This should also fix the issue with the worker not joining the cluster issue https://github.com/threefoldtech/zos/issues/1091
