### ISSUE TITLE
Stellar timeout for creation of pools

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfexplorer#239]
Sometimes when creating a pool we get a Timeout 504 error from Stellar. We already added code that retries every 1 second for the duration of 20 seconds.

Now we think this might not be enough to cover the timeout issue.

Proposed solution as referenced on the stellar official API docs:

- Increase the fee (so the tx gets prioritized)
- Retry for a longer period

**Comment by DylanVerstraete** [comment]
@robvanmieghem what are your thoughts on this?

**Comment by robvanmieghem** [comment]
increasing the fee ( until a max of 5 times base fee for example) when you retry does not harm, it's very low

**Comment by muhamadazmy** [comment]
@robvanmieghem should we also increase retry time ?

**Comment by robvanmieghem** [comment]
@muhamadazmy might help as well, if after 5 retries( when we reach our max fee) there is still a timeout, start increasing the retry time although this does not guarantee anything. I suspect this problem occurs mainly on testnet.
