### ISSUE TITLE
amount of memory allocated for the container cannot be lower then 1024 bytes

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/tfexplorer#243]
trying to reserve a container with 256 MB memory but failed with error
```
container provision schema not valid: amount of memory allocated for the container cannot be lower then 1024 bytes
```
I think this maybe a type and meant megabytes instead?

https://explorer.testnet.grid.tf/api/v1/reservations/workloads/518874

**Comment by DylanVerstraete** [comment]
Yes this is indeed a type and should be megabytes. Also you cannot reserve a container with list than 1024 megabyte memory.
