### ISSUE TITLE
Decomission of public ip fails

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/tfexplorer#247]
When a zos node sends a decomission result of a public IP, an internal server error is returned by the explorer

example:
`[+] provisiond: 2020-12-20T14:49:55Z error failed to decommission reservation 10768-1 error="failed to mark reservation as deleted: failed to release ip reservation: failed to release ip address status:500 Internal Server Error"`

**Comment by DylanVerstraete** [comment]
Confirmed fix

![Screenshot from 2020-12-21 16-45-56](https://user-images.githubusercontent.com/17138347/102794724-0eff9980-43ac-11eb-9ec0-5ed41b2eb8ce.png)
