### ISSUE TITLE
Prices API returns incorrect units

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/tfexplorer#264]
the explorer API on devnet and testnet returns different prices for cloud units than what is used when a pool is created

testnet
```                
based on prices api 291.66
from pool creation '29.1053347 TFT'
```

devnet
```                  
based on prices api 291.66
from pool creation '2.9105334 TFT'
```

**Comment by LeeSmet** [comment]
The discount based on network is indeed not reflected in the API itself, afaik this is in line with the specification. @xmonader your thoughts?
