### ISSUE TITLE
Failed to extend pool on testnet

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/tfexplorer#272]
`cause": "could not pay farmer: failed to sign and submit transaction: error submitting transaction: problem: https://stellar.org/horizon-errors/transaction_failed"`

https://explorer.testnet.grid.tf/api/v1/reservations/pools/payment/17070

I got refunded instantly

![image](https://user-images.githubusercontent.com/10658229/104119145-4ec7fa00-5336-11eb-9ec2-56165574c17f.png)

**Comment by waleedhammam** [comment]
happens more frequently now: https://explorer.testnet.grid.tf/api/v1/reservations/pools/payment/17115

**Comment by muhamadazmy** [comment]
The code to retry is only available on devent. I will update testnet and ask you to-retry

**Comment by muhamadazmy** [comment]
@waleedhammam can u give it another try on testnet, explorer has been updated.

**Comment by waleedhammam** [comment]
@muhamadazmy thanks it worked fine and deployed a 3bot

**Comment by MElborolossy** [comment]
Happen again now
https://explorer.testnet.grid.tf/api/v1/reservations/pools/payment/17181

**Comment by hossnys** [comment]
just have the same problem on testnet 
![Screenshot from 2021-01-11 13-57-50](https://user-images.githubusercontent.com/26298009/104180200-89ed2a80-5415-11eb-8d65-8d1012eca400.png)

**Comment by muhamadazmy** [comment]
@hossnys and @MElborolossy I updated explorer on testnet (again) with some code that will help us debug the issue. So I would ask you (again) to retry for hopefully the last time :)

**Comment by MElborolossy** [comment]
@muhamadazmy Still the same problem
https://explorer.testnet.grid.tf/api/v1/reservations/pools/payment/17187
![image](https://user-images.githubusercontent.com/11272864/104191050-a98c4f00-5425-11eb-87cb-7c4341ea5d38.png)

**Comment by muhamadazmy** [comment]
@MElborolossy how come this is the same payment reservation ?

**Comment by MElborolossy** [comment]
No it is different, this is 17187 but the old was 17181

**Comment by waleedhammam** [comment]
17186 worked with me, weird

**Comment by muhamadazmy** [comment]
ah sorry, pardon my dyslexia

**Comment by hossnys** [comment]
just deployed 3bot successfully on testnet 

![Screenshot from 2021-01-11 16-02-49](https://user-images.githubusercontent.com/26298009/104191715-88782e00-5426-11eb-95b9-df6fc4d11715.png)

**Comment by muhamadazmy** [comment]
@MElborolossy 

Okay the we figured out the issue (thanks @LeeSmet)
- it seems other farms (not freefarm) did not update their wallet addresses so they still using wallet from stellat testnet.
- so using other farm than freefarm on testnet will fail.
