### ISSUE TITLE
Issue transfer: pricing policy in the explorer does not take into consideration the correct algorithm

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/tfexplorer#273]
Continuation of issue opened up here: https://github.com/threefoldfoundation/info_foundation/issues/361

For history see that issue.  He'res a repetition of the last part.\

Discussed with @despiegk 
- wiki content is updated and presents the correct representation for minting purposes.  correct calculation and numbers for CU and SU calculation
- consumption rates/numbers for CU and SU needs to be adapted.  The current calculation of the explorer the same formulas for  consumption as are used for minting.  This leads to unacceptable combinations of cores and memory usage and non-ideal resource usage on farmers servers.

The explorer needs to be updates and use the following algorithm for calculating consumption

| CU (Compute Unit)   | Type 1  |  Type 2 | Type 3  | |
|---|---|---|---|---|
| GB Memory         |  4  | 8  |  2  |  |
| nr vCPU           |  2  | 1  |  4  |  |
| GB disk capacity (max for root filesystem)    |  50  | 50  |  50  | new for v 2.3 |
| Passmark Minimum  | 500  | 250 | 1000 | is performance cpu |

All chatflow allow for independent choices of nr. vCores, Memory etc, and a formula should always count is back to the minimal costs associated by combining the above CU types

For any combination of ```vCores``` and ```memory``` a algorithm should describe the best fitting CU type

Algorithm:

required cores: C 
required GB of memory: M
- find the number of CU's needed to get C cores for all three types of CU and calculate the  obtained GB's of memory
- find the number of CU's needed to get  M GB's of memory and calculate the obtained number of cores
- out of those 6 options find the solutions that match #cores >= C AND #memory >=M and then select the option that represents the minimum amount of CU's.

**Comment by muhamadazmy** [comment]
@weynandkuijpers 

The instructions are not clear what we need to do since we only have the following inputs:
CRU: number of cores (vcpu)
MRU: size of memory (gigabytes)
HRU, SRU: size of dist for HDD, and SSD

based on that we calculate the CU, and SU as following:

```
cu = round(min(MRU/4, CRU/2)*1000) / 1000
su = round((HRU/1200+SRU/300)*1000) / 1000
```

**Comment by weynandkuijpers** [comment]
My point is:  if I use one of the chatlfows and deploy a 64 cores, 1GB of memory container I get charged:
```cu=round(min((64/3), 1/4)) = 1```

Which us way of with regards to the claimed resources.

**Comment by weynandkuijpers** [comment]
@despiegk What do you thin about the proposal ^---^.  Is this something we can and should implement now or wait for the enxt release / techno update to the payment / consumption model?

**Comment by LeeSmet** [comment]
for clarification, the new pricing would look something like this:

![image](https://user-images.githubusercontent.com/22023708/105160953-1f24a900-5b11-11eb-99bb-4f800ee74893.png)

when offsetting vs the old formula:

![image](https://user-images.githubusercontent.com/22023708/105161090-44b1b280-5b11-11eb-8e72-30dadd218f5b.png)

So we will always end up with more CU in the new formula. This is also the case for "wanted" scenarios. There is an especially high increase in the 1/1 ratio (1 core / 1gb mem), which does not sound _too_ crazy.

Anyway, if we change the way CU is calculated, we should take into account how that will influence the price of a workload

**Comment by weynandkuijpers** [comment]
cool graphics - gnuplot?  All the pricing / modeling is for version 3.0 as far as I understood from yesterdays call so please do not spend anytime to implement it in 2.4/2.5 releases.

**Comment by weynandkuijpers** [comment]
Issue no longer relevant.
