### ISSUE TITLE
farmers should be able to set a default pricing for everyone and custom prices per 3bot 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfexplorer#277]
Based on earlier discussion with @despiegk 

- Farmers should be able to configure the default pricing or we use the grid standard as default if not configured
- Also the farmer should be able to define custom pricing for a customer.
- The custom pricing for customers shouldn't be available in the /farms endpoints only the default pricing

**Comment by muhamadazmy** [comment]
I wanted to freeze new features on explorer 2.4 and focus on grid 5.0! so how urgent this issue is?

**Comment by weynandkuijpers** [comment]
@muhamadazmy How much time would this take to implement the discount (or two tier pricing scheme - VDC resource pricing and non  VDC provisioning resource pricing) in release  2.4?  We need to resolve this and one way of doing this is to add the ability to provide discounts by farmers.

On another

**Comment by xmonader** [comment]
> @muhamadazmy How much time would this take to implement the discount (or two tier pricing scheme - VDC resource pricing and non VDC provisioning resource pricing) in release 2.4? We need to resolve this and one way of doing this is to add the ability to provide discounts by farmers.
> 
> We have to resolve [threefoldtech/js-sdk#2295](https://github.com/threefoldtech/js-sdk/issues/2295) before we can release 2.4.

I already prepared PRs for the explorer and the 3bot farmmgmt
