### ISSUE TITLE
devnet explorer frontend weird font spacing

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfexplorer#291]
![image](https://user-images.githubusercontent.com/41957921/109219713-a0cabf00-77c0-11eb-8549-6019e3cd0fbb.png)

![image](https://user-images.githubusercontent.com/41957921/109219757-b17b3500-77c0-11eb-9383-f21ba96e4a32.png)

**Comment by muhamadazmy** [comment]
Fixed,
