### ISSUE TITLE
more tooling for explorer management

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfexplorer#294]
as per @despiegk there's a need for more tooling for explorer management to address abuse of testnet resources and to clean up when required. 

IMPORTANT: as this is a very centralised approach we have to write some governance rules around this about.  for reporting purpose not a big deal, for taking action:  big deal.
- who can use and invoke actions
- who is needed to create consensus and sign off
- etc.

## Generic (v0.1)
- cancel workloads of a specific user
- cancel workloads of a sponsoring user (e.g all of the workloads running on sponsored pools)
- capacity usage / IP usage reporting for user / sponsoring user (probably this can be done in the SDK and to be part of the monitoring)
- TBD...

## Governance (v0.1)
- freeze workloads (eg. stop workloads, store all data, and state and take access from the owner away).
- TBD.....
 
## Maintenance (v0.1)
- migrate all  workloads of a specific 3node to another 3node (planned maintenance on 3node, hardware replacement/upgrade)
- migrate all workloads external "connections"  (webgateways) to another webgateway (maintenance)

##Monitoting (v0.1)
- specific reporting tools for resources
   - in case of IPs we have a generic reporting in js-sdk
```
JS-NG> j.tools.zos.reporting.get_public_ip_usage("devnet")                                                                                    

+========================= RESERVED IPS =========================+
user: dylanv.3bot                   |	tid: 48   |	wid: 26843
user: vdc_waleedhammam_waleed_b28552e619484a4986b9d99e45931d67|	tid: 3279 |	wid: 34429
user: vdc_omar0_volumes_7ba7420a320d4ae78a9ef46bcb5b32fb|	tid: 3164 |	wid: 30735
user: vdc_samar_samar_8db7d96c58b043a2a70a424520ccfd5e|	tid: 3270 |	wid: 34159
user: dylanv.3bot                   |	tid: 48   |	wid: 21077
user: vdc_rafybenjamin_test_0c462ee07d524ecaa1ce7260a8d57af9|	tid: 3254 |	wid: 33549
user: vdc_hanafy_sameh_72ba1416f1884340a51cedee8bc556a0|	tid: 3286 |	wid: 34586
user: vdc_waleedhammam_waleed2_4cc4228ad68e44258e8592d3d821b462|	tid: 3288 |	wid: 34746
user: vdc_samar_samar2_749278f4e236470f9c78af8e2af58f5f|	tid: 3277 |	wid: 34364
user: vdc_magidentfinal_velero_1eef0799b6a746fbaa0e6cd32897a81a|	tid: 3230 |	wid: 32719
user: vdc_dylanv_dylan_e1b38c7071f542ed9c09397485052b0a|	tid: 3263 |	wid: 33957
user: vdc_omar0_expiration_a4c8e2fbb65f4490ae39d91e07196162|	tid: 3229 |	wid: 32675
user: vdc_samehabouelsaad_test803_3191bb22fe71458c9be8602dbc46939a|	tid: 3289 |	wid: 34794
user: vdc_ahmedthabet_freemonad_c7fda9078fac469b8d31a43ffb3c5629|	tid: 3247 |	wid: 33390
user: vdc_ashraf_ashroof_575916394e1a45029cd5affe994269c6|	tid: 3297 |	wid: 35046
user: vdc_ayoubm_checkupdate_44f8be92cc90482b837670f90479dd48|	tid: 3299 |	wid: 35167
user: vdc_samehabouelsaad_test1003_0bee4cda48ff4d5d9dc1df025943e600|	tid: 3300 |	wid: 35211
user: vdc_posix_hassan_ac0e1c6ed69a42a5943525a93167e3ca|	tid: 3301 |	wid: 35428
user: vdc_essam_essamcloud_3b9131c5d5ab4e5287d1575ce79f093b|	tid: 3298 |	wid: 35105
+----------------------------------------------------------------+
busy: 19    |	    free: 10        |	total:29 
+=========================     DONE     =========================+
- TBD ....
```

**Comment by xmonader** [comment]
@weynandkuijpers please feel free to add more to the issue body^

**Comment by weynandkuijpers** [comment]
Done - refined it a bit and added some statements around governance and usage of these tools.

**Comment by muhamadazmy** [comment]
This feature is not that simple and definitely not gonna be ready for the current release. Also :
- explorer is planned to be dropped for version 3.0
- most of the code regarding "freezing" a workload is required to be done on zos itself.
- same for workload migration
