### ISSUE TITLE
minting needs to happen on all networks

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfexplorer#315]
farming needs to happen on mainnet, testnet, devnet

**Comment by muhamadazmy** [comment]
Do you mean minting ?

**Comment by muhamadazmy** [comment]
@LeeSmet please feel free to transfer this issue to the suitable repo.

**Comment by muhamadazmy** [comment]
https://wiki.threefold.io/#/threefold__farming_logic3

**Comment by LeeSmet** [comment]
Minting is active on mainnet and testnet right now

For devnet, we should  consider that devnet is latest master of zos, which might be broken. This is advertised on the zos readme. However, we also announce a 99% uptime SLA for a minting reward. This seems to lead to some potential issues imo, as a bad commit might cause  minting to not happen that month on devnet.

**Comment by sasha-astiadi** [comment]
why does minting need to happen on devnet? @despiegk @xmonader

**Comment by LeeSmet** [comment]
Minting was set up on devnet last month
