### ISSUE TITLE
Add Historical charts 

### ISSUE THREAD

**Issue by nbabenko** [threefoldtech/tfexplorer#317]
What?
We need to add historical charts graphs to show everyone how is the Grid growth is progressing.

Why?
It will help us show everyone how exactly threefold grid is progressing and it will be useful for the promotion and further growth.

Proposed implementation:
1. When you click on any of the showed main parameters, historical chart popups:
<img width="1423" alt="Screenshot 2021-05-21 at 13 23 32" src="https://user-images.githubusercontent.com/4426772/119123046-da197080-ba37-11eb-9109-32d61e8319ff.png">
2. Add separate tab with all charts

**Comment by muhamadazmy** [comment]
Explorer should not have any new features, because it's going to be dropped in later version. I will close as won't implement.
