### ISSUE TITLE
pools creation/extension takes ~ 100 seconds

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfexplorer#323]
in the VDC we create  3 pools, we noticed the process of creation, payment, success, and having the resources reflect takes about 100 seconds

**Comment by xmonader** [comment]
Telegram conv with Lee

Background of the current state:
> First, the horizon server is rate limited to 3600 requests per hour. Checking the balance of the escrow is a request, and making the payment is another. Since a user has 60 minutes to pay, an escrow will essentially trigger 60 requests in an hour, meaning we only have 60 active escrows at once (if they are not paid). In the past, we actually did hit the limit at some point (though this was a long time ago, before the capacity pools when all the reservations were paid for by themselves).

> Second, the explorer has a wallet with xlm to fund the transactions and new escrows (we don't rely on robs service). This means that every transaction also changes the sequence number on this account. Technically, we _could_ create  all transactions in parallel by checking the current sequence number and then incrementing it manually, and then sending all txes at once. This avoids some waiting for the submission and waiting for the stellar ledger to close. But that also means that txes are depending on the previous ones. If you chain 3 txes, and the first one fails, the sequence number would be wrong and the others will also fail, which is rather annoying to handle (I think). Additionally, go doesn't really allow you to control the ordering of multiple uploads, so it is possible that they arrive out of order, and that the latter ones are included in the first ledger, that ledger closes, then the others arrive, which would lead to bad sequence numbers as well.
> While it's all possible to work around, the explorer is deprecated and I feel that developing and testing this thoroughly is not worth it anymore at this point.

> Alternatively, it might be worth it to change the interval between escrow polls based on the amount of active escrows. Every time the escrows are polled, we count how many are monitored. Depending on the amount, we can increase the frequency. For example, if less than 5 escrows are active, the duration is scaled down to poll every 10 seconds. if less than 10 are active, poll every 20 secs.... that should in theory be relatively straightforward to add 


xmonader

> also probably starting the explorer with multiple wallets could help too or maybe running a private node too
> and maybe for the rate limit we can masquerade the calls coming from explorer to some sort of a relay?

Lee

> Yeah we did run a private mode for testnet at one point but that was never tested. The idea was to have a backup in case there was too much activity and we hit the rate limit. But setting that up for sure could allow much faster polls. However, that also means we (well ops) has to maintain a horizon server, keep it up to date, it uses quite some storage, and most importantly, if its not an HA setup, we introduce a single point of failure

> Multiple wallets is also a possibility, such that every call we need to pay for temprarily leases a wallet from the pool until the tx is done. That would allow multiple concurrent calls. Some changes on the explorer are needed, and we'd need to monitor multiple wallets then

> Technically it should be possible (believe its just http, and its stateless) to just implement some kind of horizon pool with a bunch of servers to relay stuff yes


So to sum it up:

1- changing the escrow poll intervals
2- having a relay to masquerade the origin of requests to get over horizon limit
3- running explorer with multiple wallets

**Comment by despiegk** [comment]
run our own horizon server?

**Comment by muhamadazmy** [comment]
To be honest, I am not sure we need to do all this to gain few seconds per transaction, when we are planning to drop the explorer anyway.

**Comment by muhamadazmy** [comment]
Horizon server already installed, we need to use it from the explorer https://github.com/threefoldtech/tfexplorer/issues/324

**Comment by OmarElawady** [comment]
After a call with @LeeSmet  @xmonader 
The following improvement was proposed:
1. Reduce poll interval to 5 seconds.
2. Bundle farmer payouts in a single transactions (up to stellar limit 100) instead of sending one by one.
3. Client payments check can be done asynchronously.

Will add the first two for now and recheck whether the 3rd should be added based on the added performance improvement.

**Comment by robvanmieghem** [comment]
If you bundle farmer payouts and 1 goes wrong, they all fail

**Comment by robvanmieghem** [comment]
For the specific case of the explorer I think our own horizon server can be a good solution since you can whitelist ip's from being rate-limited

**Comment by LeeSmet** [comment]
blocked on github.com/threefoldtech/tf_operations/issues/157 github.com/threefoldtech/tf_operations/issues/185
