### ISSUE TITLE
Pricing on explorer should be in TFT, not in dollar

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfexplorer#337]
Pricing on the wiki is in TFT and doesn't correlate with the pricing advertised on the explorer. 
Explorer should say: CU 1000TFT, SU 800 TFT, ipv4 60TFT etc. 
![photo_2021-06-29 10 25 22](https://user-images.githubusercontent.com/31733464/123763685-54a19f80-d8c4-11eb-8b95-cde69b9ac253.jpeg)
![photo_2021-06-29 10 25 19](https://user-images.githubusercontent.com/31733464/123763688-55d2cc80-d8c4-11eb-95d6-2a5104d18076.jpeg)

**Comment by LeeSmet** [comment]
Explorer is deprecated, won't implement new features
