### ISSUE TITLE
Pools payment on mainnet doesn't charge pools and takes a lot of time

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/tfexplorer#339]
Fails to extend pool

pool: https://explorer.grid.tf/api/v1/reservations/pools/3943
payment: https://explorer.grid.tf/api/v1/reservations/pools/payment/3943

Payment is paid and released but didn't charge cu, su units

![image](https://user-images.githubusercontent.com/10658229/124622564-834ae780-de7b-11eb-9dc7-4819b6632142.png)

**Update**: It charged the units after around 2 hours :)

**Comment by sabrinasadik** [comment]
is this the same issue or not? https://github.com/threefoldtech/tf_operations/issues/199

**Comment by waleedhammam** [comment]
@sabrinasadik  It's the cause for the 3Bot deployment timeout, Pools extension is failing

**Comment by sabrinasadik** [comment]
Can someone please explain what the problem here is and why it's still not resolved?

**Comment by LeeSmet** [comment]
Explorer has been updated to query multiple txes per call, and stellar horizon server is behaving properly again, pools now behave as expected.

**Comment by RafyAmgadBenjamin** [comment]
![image](https://user-images.githubusercontent.com/46320202/127485595-13926317-5a09-4843-a01b-3f4630598912.png)

https://explorer.devnet.grid.tf/api/v1/reservations/pools/13549

![image](https://user-images.githubusercontent.com/46320202/127485693-a537a3d3-0b2a-4af5-a354-cb17f3a8d6b9.png)
https://explorer.devnet.grid.tf/api/v1/reservations/pools/13551

**Comment by LeeSmet** [comment]
It seems to be related to horizon, since we are now running our own instance, but more importantly since we are moving to v3, I'll close this again.
