### ISSUE TITLE
Failed to provision pools on testnet

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/tfexplorer#340]
provisioning the pool timed out. pool_id: 29158

Amount was paid but it doesn't reflect on explorer

Payment details: https://explorer.testnet.grid.tf/api/v1/reservations/pools/payment/29158

**Comment by LeeSmet** [comment]
From what I can see, the pool has 1800 `cus`, the exact amount reserved

**Comment by waleedhammam** [comment]
> From what I can see, the pool has 1800 `cus`, the exact amount reserved

It may charge unit but after hours. I think it should be max 5 mins and payment reflect

**Comment by waleedhammam** [comment]
@LeeSmet some screenshots here https://github.com/threefoldtech/tf_operations/issues/204

**Comment by LeeSmet** [comment]
Explorers on testnet and mainnet have been updated to fetch multiple txes again per horizon query, this should speed up the provision process

**Comment by waleedhammam** [comment]
It's working now
