### ISSUE TITLE
Add message to webpage for migration

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfexplorer#345]
People who visit v2 explorer to check on their nodes should be alerted that they need to migrate to V3 ASAP. 
Please add the following message to the page:

"Make sure to [migrate your nodes](https://forum.threefold.io/t/farming-migration-grid-v2-v3/2143) to TF Grid v3 before May 1st 2022 as this tool will no longer be supported after that date."

Message should be very present & noticeable. 

Thanks!

**Comment by sabrinasadik** [comment]
@rkhamis or May 1st?

**Comment by rkhamis** [comment]
Sure. I'll update the other issue

**Comment by asamirr** [comment]
What do you think?

![image](https://user-images.githubusercontent.com/9322121/160825053-ef9fe73a-facd-4b87-847b-b38a5b42ecd3.png)

**Comment by sabrinasadik** [comment]
Go for it!

**Comment by xmonader** [comment]
it's live on explorer.threefold.io, but still needs update on explorer.grid.tf 

![image](https://user-images.githubusercontent.com/64129/163795472-12155b52-ff91-4048-bff0-7536f3ad1832.png)
