### ISSUE TITLE
dns nameserver field is always empty

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/tfexplorer#35]
For example this gateway: https://explorer.grid.tf/explorer/gateways/FVjKQYTXoUmdyhs9nKh3yqVRnsvG4bSyh6wYLHReWKeW

the nameserver value are `"dns_nameserver":["tf-gateway-prod-06.gateway.tf"]`
But on the frontend the field is empty 
![2020-04-28_1851x557_scrot](https://user-images.githubusercontent.com/303164/80493254-75d7ca80-8965-11ea-90fe-3347d6d7e9f6.png)

**Comment by DylanVerstraete** [comment]
Did not know this was going to be an array field
