### ISSUE TITLE
After failed reservation using FreeTFT, tokens are returned apart from 0.1 TFT

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/tfexplorer#38]
Normal that 0.1 TFT is used and no XLM ? And that it's not returned ? 

Before failed deployment 
<img width="638" alt="Schermafbeelding 2020-04-28 om 15 58 34" src="https://user-images.githubusercontent.com/30384423/80505271-63b15880-8974-11ea-88a1-8fede10622db.png">

After failed deployment 
<img width="636" alt="Schermafbeelding 2020-04-28 om 16 15 32" src="https://user-images.githubusercontent.com/30384423/80505196-4d0b0180-8974-11ea-8f11-72077b0db43b.png">

**Comment by LeeSmet** [comment]
In case of a failed reservation the explorer returns all funds it received. If your wallet decides to take 0.1 TFT as a transaction fee, then it never ends up on the explorer and it can obviously not be refunded. Keep in mind that our wallets (jsx and supposedly 3bot) will call a special transaction funding service, which will pay the xlm cost of the transaction for you, in exchange for 0.1 TFT. Which keeps the behavior for the user the same as on the now legacy tfchain implementation
