### ISSUE TITLE
Duplicate Nodes Showing on TF Explorer

### ISSUE THREAD

**Issue by ColinOnTheMove** [threefoldtech/tfexplorer#45]
After upgrading nodes to 2.0 duplicates are appearing on https://explorer.grid.tf/
Farm ID: dec_hk_t1
![dec_hk-t1 duplicated nodes](https://user-images.githubusercontent.com/56056976/80935330-b40a3980-8dfe-11ea-9a26-cadf12e24451.jpg)

**Comment by DylanVerstraete** [comment]
Cannot reproduce, might be a browser cache issue?

**Comment by ColinOnTheMove** [comment]
Thanks Dylan, I think you are correct that it is a caching issue, but I've cleared my browser (Chrome) and the number of nodes actually doubled, so I see 4 instances of each node now.
I wonder if the caching problem isn't at my browser level, but maybe the server feeding the API?

**Comment by DylanVerstraete** [comment]
@ColinOnTheMove did you press ctrl + shift + r in chrome?
I am trying to reproduce what you see on the screen but I just can't.

**Comment by ColinOnTheMove** [comment]
I hadn’t, I used [right hand mouse button] -> Inspect -> Application -> Clear site data.

But I have tried ctrl + shift + r now and every time I do it the number of nodes increases.

**Comment by zaibon** [comment]
I can't reproduce consistently, but I also saw the double number of nodes then normal sometime. So there is something going on and I don't think it's cache (for once :-P)

**Comment by ColinOnTheMove** [comment]
I'm seeing just 8 nodes now, which is correct. 
Maybe you managed to clear the issue from your end.

**Comment by zaibon** [comment]
I just had an even weirder case

I the explorer open in a tab, when  I switched to the tab I saw this:
![2020-05-07_1199x251_scrot](https://user-images.githubusercontent.com/303164/81338848-8eef2280-90ad-11ea-89a1-72b75b372483.png)

Then I clicked the refresh button and still got
![2020-05-07_1199x251_scrot](https://user-images.githubusercontent.com/303164/81339062-e42b3400-90ad-11ea-9570-3824181b12e0.png)



after a full refresh of the page
![2020-05-07_1232x222_scrot](https://user-images.githubusercontent.com/303164/81338844-8e568c00-90ad-11ea-9ade-e1f6ce71574f.png)
