### ISSUE TITLE
Grid deployment failures

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/tfexplorer#46]
No sure why I cannot deploy anything:
- mainnet set as the target
- trustlines build between 3sdk wallet and lobster wallet
- both wallet are able to receive tokens
- deployment fails with the following error:

![Screenshot_20200504_122639](https://user-images.githubusercontent.com/13766992/80957189-ff264b80-8e02-11ea-986d-a07e18f6acc5.png)
![Screenshot_20200504_122918](https://user-images.githubusercontent.com/13766992/80957197-03526900-8e03-11ea-9fbd-7822ed4d7aac.png)
![Screenshot_20200504_122951](https://user-images.githubusercontent.com/13766992/80957203-051c2c80-8e03-11ea-872a-6a8c8f3900dd.png)

**Comment by waleedhammam** [comment]
@zaibon I tried to deploy network on testnet worked ok, devnet no node found

Only this issue on main net it can't create a reservation

![Screenshot from 2020-05-04 13-28-40](https://user-images.githubusercontent.com/10658229/80961418-3dc00400-8e0b-11ea-802a-33aa3a43ae72.png)

**Comment by zaibon** [comment]
The problem seems to be the farm doesn't have a wallet address for the required currency. But I need to have the reservation ID to be able to track the problem.
