### ISSUE TITLE
explorer: add uptime monthly percentage

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/tfexplorer#5]
please add monthly uptime in percentage on node information

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/18591016/79687922-d91d7a80-824a-11ea-8eec-1a544bebfe18.png">

**Comment by LeeSmet** [comment]
imo this is currently not possible as the explorer does not record a history. As such, if a reboot happens the uptime calculations will be screwed for that node
