### ISSUE TITLE
explorer.grid.tf: after switching on "show offline nodes" all 171 nodes show offline

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/tfexplorer#6]
pls check. after switching on "show offline nodes" all nodes show offline or likely offline. before switching on selection 117 nodes showed online.
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/18591016/79268038-64d58680-7e9a-11ea-9b79-89969a1496f8.png">

**Comment by zaibon** [comment]
fixed by https://github.com/threefoldtech/tfexplorer/pull/3
