### ISSUE TITLE
Indicate node's health in the frontend

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfexplorer#61]
We now report the ndmz pub4 and pub6, with this information we can indicate if a node is healthy or not.

**Comment by DylanVerstraete** [comment]
related issue: https://github.com/threefoldtech/zos/issues/632

**Comment by delandtj** [comment]
healthy is : 
- a node has IPv6 that is NOT an ULA address on BOTH `zos` and `pub6` in `ndmz`.  
mostly these nodes will also have RFC1918 ip addresses, but that is not relevant.
- a node has IPv6 AND IPv4 in `ndmz` and/or `public` -> that is a supernode.

A farm can have a few nodes that have both and the rest only IPv6 -> also good

in the version we have now, we're done.

Needless to say, with a world still dragging it's IPv6 feet, we need a better solution.
