### ISSUE TITLE
GE: Resource Units Reserved display bug

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/tfexplorer#66]
Resource units reserved on a down node showing as maxint (ie. 2147483647)

![Screenshot 2020-05-11 at 13 23 07](https://user-images.githubusercontent.com/1249806/81557794-d8c95880-938c-11ea-9dd5-29fed27d84ae.png)

**Comment by DylanVerstraete** [comment]
Seems to be resolved on the explorer.

![Screenshot from 2020-06-05 13-53-41](https://user-images.githubusercontent.com/17138347/83873426-1626c900-a734-11ea-8705-a3618dd9ee3d.png)

**Comment by joefoxton** [comment]
Yes this is fixed!
