### ISSUE TITLE
Explorer should ignore updates of 0-value resource units (and uptime)

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/tfexplorer#73]
Right now there are a lot of nodes which report 0 for all resource units, as well as 0 uptime. Uptime of 0 is strange to have reported though, since that means the node reports instantly as soon as it powers on. Likewise, capacity of all 0 is logically impossible. This probably needs to be resolved in zos, but until such time, we can already disable this kind of update in the explorer.

**Comment by zaibon** [comment]
Problems comes from this function: https://github.com/threefoldtech/tfexplorer/blob/master/pkg/directory/types/node.go#L169

Which overwrite all the value for a node object. So when the node boots and identityd send information. all the field not populated by identiyd (like capacity and uptime) has a zero value
