### ISSUE TITLE
Async event subscription

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/tfexplorer#92]
There seem to be a lot of scenario's where a client is interested in one ore more particular activities on some node(s). Right now, the only way to spot these events is to observe state changes client side: On start, the client scrapes the explorer for all nodes it might be interested in. Then, after a certain interval, it scrapes the explorer again, and compares the old to the new data. This approach works, but it has some problems:

- all clients need to duplicate the logic for the events on their side
- large explorer load, because multiple clients might monitor a lot of nodes, leading to lots of requests
- polls for inactive nodes, or too frequent polls. This is mostly a problem for nodes which are not online, since their info does not change, yet the client does not know this (or the node can come online), therefore he needs to scrape the node data anyway.

Since the explorer already gets data pushed from the nodes, it is ideally suited to implement an event system. The individual handlers already know which data gets updated, and if not, a general approach where the old node data is loaded, compared to the new data, which generates a list of events, and then the new node is saved, is also possible.

In this design, we would have a protocol which allows server side messages to be pushed to an interested client (e.g. [json rpc 2](https://www.jsonrpc.org/specification)). A client connects to the explorer, over websocket or even raw tcp (websockets would allow pure javascript browser dashboards, raw tcp is slightly cheaper since there is no overhead of the websocket protocol, though both can exist next to one another), subscribes to some `topic`'s for a set of given nodes, and then just needs to send a regular heartbeat. On the explorer, the api handlers can produce the events, send them to a component which manages the subscriptions, which then filters the interesting events for a client and sends the ones it cares about.

Ofcourse we can also extend the event logic to include farm updates (not that those are too interesting, as a farm itself is mostly static afaik), and, more importantly, workloads for nodes (see threefoldtech/zos/issues/755).

The most interesting event is likely the change of a node power state (online - ofline - (re)booted - ...). This is slightly tricky, since here we don't only have a state change when data is received, but also when data is not received. An example solution would be to sweep the nodes when the explorer starts, collect online nodes in a separate service, and add a timer for these nodes. When the timer fires, the node is marked as offline. If the node sends a heartbeat, the timer is reset. Similarly, when a node sends a registration request (meaning capacityd (re)started), the node gets added to the service (if not already present) with a fresh timer.

**Comment by muhamadazmy** [comment]
I also suggest that workload `polling` also replaced with a `websocket` stream

**Comment by zaibon** [comment]
I agree we should start thinking about a system like this.
I think we have plenty of use case where this could be used:
- streaming of reservation to the nodes
- decouple the escrow / farmer logic from the explorer
- minting server

I'm not sure where jsonrpc fit in this picture though. To me a client subscribe to a specific event topic and just receives update from the server. I would try to keep the protocol to a minimum. With just ping/pong periodic message to maintain the connection open.

**Comment by LeeSmet** [comment]
For the protocol, I think we need the followng:

- A request -> response model (to open a subscription)
- Ability to send events from the server to the client, without a request made by the client
- A way to send periodic heartbeats from the client to the server (not really needed as we can rely on the uderlying connection, but this would help to remove a client who is broken on the protocol level).

JsonRPC 2 just happens to have all of this. I don't have strong feelings for it, it was just an example of something we _could_ use. It also uses json encoding for data transfer, which might be preferable to binary encoding of data (or not, depending on the requirements). 

While I agree that we should keep the protocol to a minimum, I would also very much like us to use an existing protocol and not roll something of our own, since there are very likely a lot of solutions out there already.

For the escrow, thats going to be a bit tricky though. If we do that, the explorer would not only be a server, but would also suddenly become a client to a remote escrow process. It is possible, but we'll need to expand the surface of the event module to allow this. If we go that route, we'll also need to think about an HA setup for the escrow, since running multiple processes there requires coordination between them

**Comment by muhamadazmy** [comment]
@LeeSmet I checked (quickly) the specs for json-rpc and I couldn't find  

> * Ability to send events from the server to the client, without a request made by the client

Unless I missed it out, could you point me to this in the specs.

**Comment by muhamadazmy** [comment]
I suggest we just use simple websockets for server side only events. So requests that simple rpc can just use the REST api for the explorer, and we provide other one (or multiple) ws endpoints where a node can register for one (or more) events. 

For simplicity this can be one endpoint per event (for example /ws/workloads, and others...)

> I don't get some parts in the original issue description.  For example: Are there are use cases for clients waiting for changes of node state? I mean who is interested in this and why ?

**Comment by zaibon** [comment]
> I suggest we just use simple websockets for server side only events. So requests that simple rpc can just use the REST api for the explorer, and we provide other one (or multiple) ws endpoints where a node can register for one (or more) events.
For simplicity this can be one endpoint per event (for example /ws/workloads, and others...)

I was seeing it the same way. We just add some endpoint to the API that are websocket endpoint. Depending what URL you reach you already know what object you are going to get back. I like this cause it integrate into the REST API transparently. You also don't need any "protocol" per say. Just make sure you have ping/pong message flowing to detect disconnection and maintain connection opens, and the client reads the socket to received message from the server.

I think this can be applied for any use case we have:
- workloads: we just send reservation to the clients
- minting: not sure exactly what we need to send to the client for this? @LeeSmet 
- escrow: we just send reservation that are ready to pay

**Comment by LeeSmet** [comment]
The reason I mentioned json-rpc 2 is because it is also used by the bitcoin electrum protocol, where a client subscribes to some topics, and then the server sends it events as they happen. Whics is the same workflow we have. Ethereum uses it as well for a similar usecase afaik. If we just send regular json back to the user, then that would be simpler to implement (seems there is indeed not really a generic jsonrpc 2 package in go for some reason), but at the same time, it means we have no flexibility and any change in logic could break existing clients.

Also to get 1 thing clear, this is merely the application protocol, and does not imply anything about the underlying transport. I agree that this should happen over websockets for maximum compatibility.

I'm also more of a fan of having a single endpoint rather than a bunch of them. In case of the latter, a client that wants more than 1 topic to be streamed would need to open multiple connections, which in turn means we need to have multiple read and write buffers for that client, meaning we increase memory usage on our end (and their end).

And while we are at it, I'd like to have some (simple) metrics to monitor this thing. At least the amount of current connections, and possibly some data about the amount and types of events we (try to) send. Throughput metrics would be neat as well, if possible without too much hassle :blush:

**Comment by zaibon** [comment]
Ok I see more where you are going with this now.  Should we try to come up with some actual design for one of our use cases and see how it shape and if we can apply to all of them ?

> And while we are at it, I'd like to have some (simple) metrics to monitor this thing. At least the amount of current connections, and possibly some data about the amount and types of events we (try to) send. Throughput metrics would be neat as well, if possible without too much hassle blush

Adding some more metrics to the prometheus endpoint shouldn't be a problem.

**Comment by LeeSmet** [comment]
Ok, so one thing that immediately comes to mind is some kind of farmer dashboard. Let's say we have a farmer, named Fred, who has a decently sized farm of about 20 nodes. They sit in a server rack in his closet somewhere. Now Fred here thinks this can be a good source of income next to his regular job. Fred is a bit of a technical guy, so he installs a tablet in his office and hangs it on the wall, on which he runs some kind of dashboard to show him the status of his nodes, as well as some other data he finds useful. Since this feature is exposed over websockets, the entire dashboard can live as a javescript browser application.

Fred decides that he first wants to see a list of all his nodes and their status. He does not want to deal with adding all nodes manually. As such, he simply inputs his farmer ID, and loops over the nodes, filtering all nodes which have his ID in the farmer ID field. He opens the event stream connection, and subscribes to events from these nodes. Very important, he wants to subscribe to some kind of `uptime status event`. He want to display if the node is online or not, and wants to have this status indicator reactive in real time without pulling the node every 10 minutes. Ofcourse Fred also wants to see what versions his nodes are running, as he wants to make sure he always has the latest and greatest code running on his nodes.

Since Fred recognizes the potential, he also wants to have some insight in how his nodes are used. After all, if he notices a particular pattern in the usage of his capacity, he can later add new capacity which is tailer specifically to the consumer usage of his nodes. So Fred adds some counters on his dashboard which show how much of the capacity of his nodes is used, similar to the current grid explorer. Once again, he adds subscriptions on his websocket event stream, for a particular kind of event which relates to these counters.

But Fred realizes that these values don't mean a lot without context. So he also adds the amount of volumes, containers,... etc are deployed on a node, opening yet another subscription. This really allows him to see what exactly is going on on his nodes, and what kind of hardware he needs to add in the future to get maximum utilization, and thus rewards, for his farm.

Now, while developing this, Fred realizes that there is more to it than that. Having 10 kubernetes nodes is cool, but are these the same 10 nodes every day? maybe they live for a day only, and someone just creates new nodes every night while Fred is not looking. In fact, he starts to wonder who is utilizing his nodes and how. Is it a small group of people who just happen to deploy a lot on his nodes? Are there a bunch of customers who deploy something once, and maybe they come back later but there is a lot experimentation going on? How long do the workloads live? Are the workloads deployed only on his farm, or are his nodes part of a larger system? So to this end, Fred decides to also subscribe to the reservation events. He wants to show a list with the latest 10 or so reservations which are deploying something on at least one of his nodes (and possibly someone elses), how long it is reserved for, who reserved it, and how much each reservation will earn him. And naturally, he wants to get an alert if someone decides to cancel a reservation.

While coding this up, Fred notices that there is already quite a bit of usage on his nodes, and that an expansion of his farm is definitely possible in the near future. Since he does not want to touch his dashboard to pick up the new nodes if at all possible, he also subscribes on the `new nodes event` stream. When a new node is picked up, he checks the farmer ID, and if it matches, he updates relevant subscriptions to also stream events for this node, and adds it in his UI.

Keep in mind that we estabished farmer Fred has a day job at another company. Lets assume that this small business has an equivalent internet setup as a regular house. As such, he'd like it to do this without blowing the amount of active connections going out of the firewall through the roof :)
